name: Terraform Format & Validate

on:
  pull_request:
    branches: [main]
   
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform (v5.x.x to <6.0.0)
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '>=5.0.0, <6.0.0'

      - name: Terraform Init (Install Providers)
        run: terraform init 

      - name: Terraform fmt (Check Formatting)
        run: terraform fmt -check -recursive

      - name: Set Terraform Environment Variables
        run: |
          export TF_VAR_region="${{ secrets.REGION }}"
          export TF_VAR_vpc_cidr="${{ secrets.VPC_CIDR }}"
          export TF_VAR_public_subnets="${{ secrets.PUBLIC_SUBNETS }}"
          export TF_VAR_private_subnets="${{ secrets.PRIVATE_SUBNETS }}"
          export TF_VAR_aws_profile="${{ secrets.AWS_PROFILE }}"
          export TF_VAR_custom_ami="${{ secrets.CUSTOM_AMI }}"
          export TF_VAR_db_dialect="${{ secrets.DB_DIALECT }}"
          export TF_VAR_db_name="${{ secrets.DB_NAME }}"
          export TF_VAR_db_username="${{ secrets.DB_USERNAME }}"
          export TF_VAR_db_password="${{ secrets.DB_PASSWORD }}"
          export TF_VAR_zone_id="${{ secrets.ZONE_ID }}"
          echo "Terraform variables set from GitHub Secrets"
          env | grep TF_VAR_  # Debugging step to verify variables are set

      - name: Terraform validate (Check Configuration)
        run: terraform validate
