name: Terraform Format & Validate

on:
  pull_request:
    branches: [main]
   
jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform (v5.x.x to <6.0.0)
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: '>=5.0.0, <6.0.0'

      - name: Terraform Init (Install Providers)
        run: terraform init 

      - name: Terraform fmt (Check Formatting)
        run: terraform fmt -check -recursive

      - name: Set Terraform Environment Variables
        env:
          TF_VAR_region: ${{ secrets.REGION }}
          TF_VAR_vpc_cidr: ${{ secrets.VPC_CIDR }}
          TF_VAR_public_subnets: ${{ secrets.PUBLIC_SUBNETS }}
          TF_VAR_private_subnets: ${{ secrets.PRIVATE_SUBNETS }}
          TF_VAR_aws_profile: ${{ secrets.AWS_PROFILE }}
          TF_VAR_custom_ami: ${{ secrets.CUSTOM_AMI }}
        run: |
          echo "Terraform variables set from GitHub Secrets"

      - name: Debug Environment Variables (Optional)
        run: env | grep TF_VAR_

      - name: Terraform validate (Check Configuration)
        run: terraform validate
